# Generated by Django 4.2.11 on 2024-04-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0002_alter_specialty_code_alter_specialty_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
