# Generated by Django 4.2.11 on 2024-04-18 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0004_alter_specialty_code_alter_specialty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='specialty',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='journal_app.specialty'),
            preserve_default=False,
        ),
    ]
