# Generated by Django 4.2.11 on 2024-04-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0007_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
