# Generated by Django 4.2.11 on 2024-05-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0015_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
