# Generated by Django 4.2.11 on 2024-05-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0016_teacher_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mark', models.CharField(max_length=1)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal_app.discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal_app.student')),
            ],
        ),
    ]
