# Generated by Django 4.2.11 on 2024-05-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0017_discipline_journalentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='date',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='day',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='month',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
