# Generated by Django 4.2.11 on 2024-05-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0018_remove_journalentry_date_journalentry_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
