# Generated by Django 4.2.11 on 2024-06-04 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0022_alter_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal_app.journalentry')),
            ],
        ),
    ]
