# Generated by Django 4.2.11 on 2024-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0023_journalentryday'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='group',
            field=models.ManyToManyField(to='journal_app.group'),
        ),
    ]
