# Generated by Django 4.2.11 on 2024-06-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0024_discipline_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal_app.discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal_app.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journal_app.lesson'),
            preserve_default=False,
        ),
    ]
