# Generated by Django 4.2.11 on 2024-06-09 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0030_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='day',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mark',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal_app.teacher'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
