# Generated by Django 4.2.11 on 2024-06-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0031_alter_journalentry_day_alter_journalentry_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
