# Generated by Django 4.2.11 on 2024-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0032_alter_journalentry_day_alter_journalentry_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
