# Generated by Django 4.2.11 on 2024-06-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0033_alter_lesson_date_alter_lesson_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='month',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='JournalEntryDay',
        ),
    ]
