# Generated by Django 4.2.11 on 2024-06-13 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0034_alter_journalentry_month_alter_journalentry_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal_app.lesson'),
        ),
    ]
