# Generated by Django 4.2.11 on 2024-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0035_alter_journalentry_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mark',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('student', 'discipline', 'day', 'month', 'year')},
        ),
    ]
