# Generated by Django 4.2.11 on 2024-06-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0036_alter_journalentry_day_alter_journalentry_mark_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mark',
            field=models.CharField(max_length=5),
        ),
    ]
